easy_admin:
  entities:
    Membre:
      class: App\Entity\Membre
  design:
    brand_color: 'blue'
    assets:
      css:
        - 'bundles/app/css/custom_admin.css'
      js:
        - 'bundles/app/js/custom_admin.js'
      favicon: '/img/favicon.png'

    menu:
      - label: 'Dashboard'
        icon: 'tachometer-alt'
        children:
          - {entity: 'Article', icon: 'shopping-bag', label: 'Articles', css_class: 'menu--product', default: true }
          - {entity: 'Membre', icon: 'users', label: 'Membres', children: ['admin', 'clients']}
