easy_admin:
  entities:
    Article:
      class: App\Entity\Produit
      controller: App\Controller\ProduitController
      label: 'Produits'
      help: 'Vous etes dans la section produit'
      #image_base_path: '/img'
      #Changer le titre des actions
      new:
        title:  'Ajouter un produit'
        form_options: { validation_groups: ['Default', 'Produit'] }
      edit:
        title:  'Modifier un produit'
        form_options: { validation_groups: ['Default'] }
      actions:
        - {name: 'search', icon: 'search', label: false}

        #templates:
        #edit: 'admin/produit/edit.html.twig'
      list:
        title: 'Derniers produits ajoutés'
        help: null
        #Champs affichés en listant les articles
        fields: ['name', {property: 'image1', type: 'image', base_path: '%app.path.product_images%', label: 'Image principale'}, 'spotlight', 'special']

      show:
        fields:
          - { property: 'image', type: 'image', base_path: '%app.path.product_images%' }


        #Personnalisation des boutons
        actions:
          - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-secondary'}
          - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}
          - {name: 'new', icon: 'plus', label: false, title: 'Ajouter' }

      #Champs affichés dans le formulaire d'ajout
      form:
        fields:
          - {property: 'name'}
          - {property: 'description'}
          - {property: 'slug'}
          - {property: 'specification'}
          - {property: 'reference'}
          - {property: 'imageFile1', type: 'vich_image', label: 'Image principale' , type_options: { required: true , help: 'Ce champs est obligatoire, veuillez ajouter une image'} }
          - {property: 'imageFile2', type: 'vich_image', label: 'Image 2'}
          - {property: 'imageFile3', type: 'vich_image', label: 'Image 3'}
          - {property: 'imageFile4', type: 'vich_image', label: 'Image 4'}
          - {property: 'imageFile5', type: 'vich_image', label: 'Image 5'}
          - {property: 'imageFile6', type: 'vich_image', label: 'Image 6'}
          - {property: 'imageFile7', type: 'vich_image', label: 'Image 7'}
          - {property: 'spotlight'}
          - {property: 'categorie'}
          - {property: 'protocol'}
          - {property: 'date', type: 'datetime'}
          - {property: 'security'}
